### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 1, in <module>     import discord, os, platform, nacl ModuleNotFoundError: No module named 'nacl'

### ISSUE THREAD

**Issue by GamerPTS199** [hirusha-adi/Discord-Account-Always-Onlie#2]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import discord, os, platform, nacl
ModuleNotFoundError: No module named 'nacl'

**Comment by hirusha-adi** [comment]
please run these commands

# Linux
```
python3 -m pip install PyNacl
```

# Windows
```
py -m pip install PyNacl
```

this should fix it
thank you
